### ISSUE TITLE
Faturada Jquery ile eklenen satırlarda ürün adı olarak canlı arama yaparak çıkan sonucu seçkmek 

### ISSUE THREAD

**Issue by Ademgenc53** [borasahin/phplivesearch#1]
Merhaba,
Bu canlı arama kodunuzu kullandım teşekkür ederim, çok güzel

Ancak bir yerdede kullanmak istiyorum
Bu fatura sistemi kullanıyorum: https://phpzag.com/demo/build-invoice-system-with-php-mysql-demo/
Eklenen satırlarda ürün adını canlı seçmek istiyorum javascript/jquery bilmediğim için bir şeyler yapmaya çalıştım ama olmadı yardımcı olabilirmisiniz?

Kolay gelsin

**Comment by borasahin** [comment]
Merhaba,

Projenize baktım. Orada olana göre basit bir örnek hazırladım aşağıda sanıyorum bu şekilde uygulama yaparsanız sonuç alabilirsiniz. 


```
<!-- PROJE KODLARI -->
<td>
	<input type="text" name="productCode[]" id="productCode_1" onchange="getProduct(this.value,'#productCode_1')" data-item-id="productCode_1" class="form-control" autocomplete="off">
	<ul class="list-group liveresult"></ul>
</td>
<!-- PROJE KODLARI -->
<script type="text/javascript">
	getProduct(value,id){
        var inputVal = value
        var resultDropdown = $(this).siblings(".liveresult");
        if(inputVal.length){
        	/* live-search.php > SQL sorgusunun olduğu sonuç döndürecek sayfanız. örnek olarak live-search.php dosyasına bakabilirsin. */
            $.get('live-search.php', {term: inputVal}).done(function(data){
                resultDropdown.html(data);
            });
        }else{
            resultDropdown.empty();
        }
        $(document).on("click", ".liveresult li", function(){
            $(this).parents(id).find('input[type="text"]').val($(this).text());
            $(this).parent(".liveresult").empty();
        });
    }
</script>
```

Veya çok fazla ürün verisi yoksa Bootstrap Select kullanabilirsiniz.

+ Satır eklediğinizde mutlaka invoice.js'de #addRows fonksiyonunuza aşağıdaki satırı dahil etmeyi unutmayın.

`$('.selectpicker').selectpicker('refresh');`

https://github.com/snapappointments/bootstrap-select/

**Comment by Ademgenc53** [comment]
Yardımınız için çok teşekkür ederim,

Bu satırı `var resultDropdown = $(this).siblings(".liveresult");`
Bu şekilde değiştirdiğimde listeleniyor` var resultDropdown = $(".liveresult");`

Bu satırı `$(this).parents(id).find('input[type="text"]').val($(this).text());`
Bu şekilde `$("#baslik").val($(this).text());`

Bu satırı `$(this).parent(".liveresult").empty();`
Bu şekilde `$(".liveresult").empty();`

Diğer kullandığım alanlarda da böyle değiştirerek çalıştı

Bu fatura projemde
Ayrıca bu çalışmadı `onchange="getProduct(this.value,'#productCode_1')"`
Bu şekilde değiştirdimdi çalıştı `onkeyup="getProduct(this.value,'#productCode_1')"`

ürün adını seçiliyorum input a ekliyor ama birden fazla satır olunca son seçilen tüm urun adı alanlara ekliyor, yani hepsi aynı isim oluyor
javascript bilmediğim için yorum yapamıyorum ama onchange yerine onkeyup yaptığım için olabilir mi?

**Comment by borasahin** [comment]
Merhaba,

`getProduct(this.value,'#productCode_1')`

Bu fonksiyon için 2. parametre olan **#productCode_1** değerinin her satırda değişiyor olması gerekli 1 2 3 gibi o zaman sorun çözülecektir diye düşünüyorum.

**Comment by Ademgenc53** [comment]
Tabi değişiyor varsayılan il satır 1 dır her eklenen satır 2, 3,4 gibi devam ediyor
Sorunu buldum galiba
Her satırın input urun adı altında sonuç listesini ekliyorum bunun class adınada ID atadım 
```
sadece_id = id.replace("#urun_adi_",'');
$(".liveresult_" + sadece_id);
```
Yaptım her satırı bağımsız urun adını ekledi
Şimdi bu css yi javascript ile ekleyebilsem tam olacak diye düşünüyorum
```
    .liveresult li{
        cursor: pointer;
        
    }
    .liveresult li:hover{
        background: #f2f2f2;
    }
```
```
$(".xxxxx_" + sadece_id).css("cursor","pointer");
$(".xxxxxxx_" + sadece_id).css("background-color","#f2f2f2");
```

**Comment by borasahin** [comment]
Eklediğiniz <tr> satırında <tr id="satir_id"> gibi de yapabilirsiniz. jquery içinde de tr#12 #productCode_1 gibi devam edebilirsiniz sanıyorum bu da problemi çözecektir.

**Comment by Ademgenc53** [comment]
Acemi olduğumuz için tam anlayamadım ama liveresult class a _1, _2 gibi her satır kendi aramasında sonucu gösterdim ve seçtiğimde sorunsuz olarak input içine ekledi diğer input içerikler değişmeden bu tamam

Şimdi sadece sonuç listesinde mause üzerine gelince arka plan rengi ve el simgesi görülmesi için css atamak lazım ama class adında _1, _2 olduğu için javascrip içinden atamak lazım
**li** ve **li:hover** olunca aşağıdaki css nasıl yapmak lazım
```
$(".liveresult_" + sadece_id).css("cursor","pointer"); 
$(".liveresult_" + sadece_id).css("background-color","#f2f2f2");
```

**Comment by borasahin** [comment]
```
<ul class="search_result liveresult_1">
<li>Fo</i>
</ul>
```

ul için sabit bir sonuç alan 2. bir class ekleyin. search_result gibi. sonra css ile tanımlama yapabilirsiniz. JS ile ek olarak uğraşmanıza gerek yok

**Comment by Ademgenc53** [comment]
Tamam anladım ve yaptım tam istediğim gibi çalışıyor
Çok teşekkür ederim kardeşim Allah razı olsun
Kolay gelsin
